export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_SUCCEEDED = 'DELETE_SUCCEEDED';

export const ADD_NEWS = 'ADD_NEWS';
export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_SUCCEEDED = 'FETCH_NEWS_SUCCEEDED';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';